trigger:
  - main

pool:
  name: Agent server

variables:
  buildConfiguration: 'Release'
  deployPath: 'D:\Public\247\api'
  publishOutputPath: '$(Build.ArtifactStagingDirectory)/publish'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET 10 SDK'
  inputs:
    packageType: 'sdk'
    version: '10.0.x'

- script: dotnet restore Api.sln
  displayName: 'Restore packages'

- script: dotnet publish Api/Api.csproj -c $(buildConfiguration) -o $(publishOutputPath) --no-restore
  displayName: 'Publish Api'

- task: CopyFiles@2
  displayName: 'Copy Files to Deploy Directory'
  inputs:
    sourceFolder: '$(publishOutputPath)'
    contents: '**'
    targetFolder: '$(deployPath)'
    cleanTargetFolder: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
